"""epic1 foundation schema

Revision ID: 50380feee754
Revises: 
Create Date: 2026-09-17 12:24:43.059408

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0001_epic1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('venues',
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('business_day_boundary', sa.Time(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venues_organisation_id'), 'venues', ['organisation_id'], unique=False)
    op.create_table('equipment_items',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('repair_contact', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='equipment_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_items_venue_id'), 'equipment_items', ['venue_id'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'ops_manager', 'head_chef', 'sous_chef', 'line_staff', name='membership_role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'venue_id', name='uq_membership_user_venue')
    )
    op.create_index(op.f('ix_memberships_user_id'), 'memberships', ['user_id'], unique=False)
    op.create_index(op.f('ix_memberships_venue_id'), 'memberships', ['venue_id'], unique=False)
    op.create_table('menu_items',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_items_venue_id'), 'menu_items', ['venue_id'], unique=False)
    op.create_table('recipes',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipes_venue_id'), 'recipes', ['venue_id'], unique=False)
    op.create_table('service_days',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('business_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('planned', 'open', 'closed', name='service_day_status'), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('venue_id', 'business_date', name='uq_service_day_venue_date')
    )
    op.create_index(op.f('ix_service_days_venue_id'), 'service_days', ['venue_id'], unique=False)
    op.create_table('staff',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_user_id'), 'staff', ['user_id'], unique=False)
    op.create_index(op.f('ix_staff_venue_id'), 'staff', ['venue_id'], unique=False)
    op.create_table('stations',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stations_venue_id'), 'stations', ['venue_id'], unique=False)
    op.create_table('suppliers',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('contact_email', sa.String(length=320), nullable=True),
    sa.Column('order_days', sa.String(length=40), nullable=True),
    sa.Column('cutoff_time', sa.Time(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_venue_id'), 'suppliers', ['venue_id'], unique=False)
    op.create_table('audit_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organisation_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=True),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=80), nullable=False),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organisation_id'], ['organisations.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_events_actor_user_id'), 'audit_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_events_organisation_id'), 'audit_events', ['organisation_id'], unique=False)
    op.create_index(op.f('ix_audit_events_recorded_at'), 'audit_events', ['recorded_at'], unique=False)
    op.create_index(op.f('ix_audit_events_service_day_id'), 'audit_events', ['service_day_id'], unique=False)
    op.create_index(op.f('ix_audit_events_venue_id'), 'audit_events', ['venue_id'], unique=False)
    op.create_table('ingredients',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('ordering_unit', sa.String(length=40), nullable=False),
    sa.Column('preferred_supplier_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['preferred_supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingredients_preferred_supplier_id'), 'ingredients', ['preferred_supplier_id'], unique=False)
    op.create_index(op.f('ix_ingredients_venue_id'), 'ingredients', ['venue_id'], unique=False)
    op.create_table('menu_item_recipes',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('menu_item_id', 'recipe_id')
    )
    op.create_table('recipe_versions',
    sa.Column('recipe_id', sa.UUID(), nullable=False),
    sa.Column('version_no', sa.Integer(), nullable=False),
    sa.Column('yield_qty', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('yield_unit', sa.String(length=40), nullable=True),
    sa.Column('prep_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['recipe_id'], ['recipes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipe_id', 'version_no', name='uq_recipe_version_number')
    )
    op.create_index(op.f('ix_recipe_versions_recipe_id'), 'recipe_versions', ['recipe_id'], unique=False)
    op.create_table('staff_skills',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('trained', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staff_id', 'station_id', name='uq_staff_skill_staff_station')
    )
    op.create_index(op.f('ix_staff_skills_staff_id'), 'staff_skills', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_skills_station_id'), 'staff_skills', ['station_id'], unique=False)
    op.create_table('station_coverage_rules',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.Time(), nullable=False),
    sa.Column('window_end', sa.Time(), nullable=False),
    sa.Column('minimum_staff', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('station_id', 'day_of_week', 'window_start', 'window_end', name='uq_coverage_rule_station_day_window')
    )
    op.create_index(op.f('ix_station_coverage_rules_station_id'), 'station_coverage_rules', ['station_id'], unique=False)
    op.create_index(op.f('ix_station_coverage_rules_venue_id'), 'station_coverage_rules', ['venue_id'], unique=False)
    op.create_table('recipe_ingredients',
    sa.Column('recipe_version_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['recipe_version_id'], ['recipe_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recipe_ingredients_ingredient_id'), 'recipe_ingredients', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_recipe_ingredients_recipe_version_id'), 'recipe_ingredients', ['recipe_version_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recipe_ingredients_recipe_version_id'), table_name='recipe_ingredients')
    op.drop_index(op.f('ix_recipe_ingredients_ingredient_id'), table_name='recipe_ingredients')
    op.drop_table('recipe_ingredients')
    op.drop_index(op.f('ix_station_coverage_rules_venue_id'), table_name='station_coverage_rules')
    op.drop_index(op.f('ix_station_coverage_rules_station_id'), table_name='station_coverage_rules')
    op.drop_table('station_coverage_rules')
    op.drop_index(op.f('ix_staff_skills_station_id'), table_name='staff_skills')
    op.drop_index(op.f('ix_staff_skills_staff_id'), table_name='staff_skills')
    op.drop_table('staff_skills')
    op.drop_index(op.f('ix_recipe_versions_recipe_id'), table_name='recipe_versions')
    op.drop_table('recipe_versions')
    op.drop_table('menu_item_recipes')
    op.drop_index(op.f('ix_ingredients_venue_id'), table_name='ingredients')
    op.drop_index(op.f('ix_ingredients_preferred_supplier_id'), table_name='ingredients')
    op.drop_table('ingredients')
    op.drop_index(op.f('ix_audit_events_venue_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_service_day_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_recorded_at'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_organisation_id'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_actor_user_id'), table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_index(op.f('ix_suppliers_venue_id'), table_name='suppliers')
    op.drop_table('suppliers')
    op.drop_index(op.f('ix_stations_venue_id'), table_name='stations')
    op.drop_table('stations')
    op.drop_index(op.f('ix_staff_venue_id'), table_name='staff')
    op.drop_index(op.f('ix_staff_user_id'), table_name='staff')
    op.drop_table('staff')
    op.drop_index(op.f('ix_service_days_venue_id'), table_name='service_days')
    op.drop_table('service_days')
    op.drop_index(op.f('ix_recipes_venue_id'), table_name='recipes')
    op.drop_table('recipes')
    op.drop_index(op.f('ix_menu_items_venue_id'), table_name='menu_items')
    op.drop_table('menu_items')
    op.drop_index(op.f('ix_memberships_venue_id'), table_name='memberships')
    op.drop_index(op.f('ix_memberships_user_id'), table_name='memberships')
    op.drop_table('memberships')
    op.drop_index(op.f('ix_equipment_items_venue_id'), table_name='equipment_items')
    op.drop_table('equipment_items')
    op.drop_index(op.f('ix_venues_organisation_id'), table_name='venues')
    op.drop_table('venues')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('organisations')
    # ### end Alembic commands ###

    # Alembic's autogenerate does NOT drop Postgres ENUM types when the
    # tables that used them are dropped (a real gap, not a hypothetical one —
    # verified: re-running `alembic upgrade head` after a downgrade failed
    # with "type already exists" until these three lines were added).
    sa.Enum(name="membership_role").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="service_day_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="equipment_status").drop(op.get_bind(), checkfirst=True)
