"""epic2 roster

Revision ID: 0003_epic2
Revises: 0002_epic1_step4
Create Date: 2026-09-17 13:49:00.606191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0003_epic2'
down_revision = '0002_epic1_step4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('draft', 'published', 'cancelled', name='shift_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_service_day_id'), 'shifts', ['service_day_id'], unique=False)
    op.create_index(op.f('ix_shifts_staff_id'), 'shifts', ['staff_id'], unique=False)
    op.create_index(op.f('ix_shifts_station_id'), 'shifts', ['station_id'], unique=False)
    op.create_index(op.f('ix_shifts_venue_id'), 'shifts', ['venue_id'], unique=False)
    op.create_table('staff_links',
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_links_shift_id'), 'staff_links', ['shift_id'], unique=False)
    op.create_index(op.f('ix_staff_links_staff_id'), 'staff_links', ['staff_id'], unique=False)
    op.create_index(op.f('ix_staff_links_token_hash'), 'staff_links', ['token_hash'], unique=True)
    op.create_table('staff_responses',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'declined', name='staff_response_status'), nullable=False),
    sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('responded_via', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.ForeignKeyConstraint(['staff_id'], ['staff.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staff_responses_shift_id'), 'staff_responses', ['shift_id'], unique=True)
    op.create_index(op.f('ix_staff_responses_staff_id'), 'staff_responses', ['staff_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_staff_responses_staff_id'), table_name='staff_responses')
    op.drop_index(op.f('ix_staff_responses_shift_id'), table_name='staff_responses')
    op.drop_table('staff_responses')
    op.drop_index(op.f('ix_staff_links_token_hash'), table_name='staff_links')
    op.drop_index(op.f('ix_staff_links_staff_id'), table_name='staff_links')
    op.drop_index(op.f('ix_staff_links_shift_id'), table_name='staff_links')
    op.drop_table('staff_links')
    op.drop_index(op.f('ix_shifts_venue_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_station_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_staff_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_service_day_id'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###

    # Same real gap as 0001's downgrade — Alembic's autogenerate does NOT
    # drop Postgres ENUM types when the tables using them are dropped, so
    # upgrade -> downgrade -> upgrade fails with "type already exists"
    # without these.
    sa.Enum(name="staff_response_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="shift_status").drop(op.get_bind(), checkfirst=True)
