"""epic3 attendance

Revision ID: 0004_epic3
Revises: 0003_epic2
Create Date: 2026-09-17 14:05:21.482262

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0004_epic3'
down_revision = '0003_epic2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_events',
    sa.Column('shift_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('present', 'late', 'absent', 'sick', name='attendance_status'), nullable=False),
    sa.Column('source', sa.Enum('chef', 'staff_link', name='attendance_source'), nullable=False),
    sa.Column('actor_user_id', sa.UUID(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attendance_events_actor_user_id'), 'attendance_events', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_attendance_events_shift_id'), 'attendance_events', ['shift_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attendance_events_shift_id'), table_name='attendance_events')
    op.drop_index(op.f('ix_attendance_events_actor_user_id'), table_name='attendance_events')
    op.drop_table('attendance_events')
    # ### end Alembic commands ###

    sa.Enum(name="attendance_source").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="attendance_status").drop(op.get_bind(), checkfirst=True)
