"""epic4 prep plan

Revision ID: 0005_epic4
Revises: 0004_epic3
Create Date: 2026-09-17 14:10:52.140960

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0005_epic4'
down_revision = '0004_epic3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prep_templates',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_templates_venue_id'), 'prep_templates', ['venue_id'], unique=False)
    op.create_table('prep_template_items',
    sa.Column('template_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['prep_templates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_template_items_station_id'), 'prep_template_items', ['station_id'], unique=False)
    op.create_index(op.f('ix_prep_template_items_template_id'), 'prep_template_items', ['template_id'], unique=False)
    op.create_table('prep_tasks',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=False),
    sa.Column('station_id', sa.UUID(), nullable=False),
    sa.Column('item', sa.String(length=200), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'in_progress', 'done', 'blocked', name='prep_task_status'), nullable=False),
    sa.Column('template_item_id', sa.UUID(), nullable=True),
    sa.Column('carried_from_task_id', sa.UUID(), nullable=True),
    sa.Column('carried_to_task_id', sa.UUID(), nullable=True),
    sa.Column('carry_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['carried_from_task_id'], ['prep_tasks.id'], ),
    sa.ForeignKeyConstraint(['carried_to_task_id'], ['prep_tasks.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.ForeignKeyConstraint(['station_id'], ['stations.id'], ),
    sa.ForeignKeyConstraint(['template_item_id'], ['prep_template_items.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prep_tasks_carried_from_task_id'), 'prep_tasks', ['carried_from_task_id'], unique=False)
    op.create_index(op.f('ix_prep_tasks_carried_to_task_id'), 'prep_tasks', ['carried_to_task_id'], unique=False)
    op.create_index(op.f('ix_prep_tasks_service_day_id'), 'prep_tasks', ['service_day_id'], unique=False)
    op.create_index(op.f('ix_prep_tasks_station_id'), 'prep_tasks', ['station_id'], unique=False)
    op.create_index(op.f('ix_prep_tasks_template_item_id'), 'prep_tasks', ['template_item_id'], unique=False)
    op.create_index(op.f('ix_prep_tasks_venue_id'), 'prep_tasks', ['venue_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prep_tasks_venue_id'), table_name='prep_tasks')
    op.drop_index(op.f('ix_prep_tasks_template_item_id'), table_name='prep_tasks')
    op.drop_index(op.f('ix_prep_tasks_station_id'), table_name='prep_tasks')
    op.drop_index(op.f('ix_prep_tasks_service_day_id'), table_name='prep_tasks')
    op.drop_index(op.f('ix_prep_tasks_carried_to_task_id'), table_name='prep_tasks')
    op.drop_index(op.f('ix_prep_tasks_carried_from_task_id'), table_name='prep_tasks')
    op.drop_table('prep_tasks')
    op.drop_index(op.f('ix_prep_template_items_template_id'), table_name='prep_template_items')
    op.drop_index(op.f('ix_prep_template_items_station_id'), table_name='prep_template_items')
    op.drop_table('prep_template_items')
    op.drop_index(op.f('ix_prep_templates_venue_id'), table_name='prep_templates')
    op.drop_table('prep_templates')
    # ### end Alembic commands ###

    sa.Enum(name="prep_task_status").drop(op.get_bind(), checkfirst=True)
