"""epic5 supplier orders

Revision ID: 0006_epic5
Revises: 0005_epic4
Create Date: 2026-09-17 14:27:54.085124

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006_epic5'
down_revision = '0005_epic4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_orders',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('supplier_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('draft', 'sending', 'sent', 'send_failed', name='purchase_order_status'), nullable=False),
    sa.Column('required_delivery_date', sa.Date(), nullable=True),
    sa.Column('order_cycle', sa.String(length=60), nullable=True),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_by', sa.UUID(), nullable=True),
    sa.Column('provider_message_id', sa.String(length=200), nullable=True),
    sa.Column('recipient_snapshot', sa.String(length=320), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('delivery_status', sa.Enum('pending', 'received', 'partially_received', name='delivery_status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['sent_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    op.create_index(op.f('ix_purchase_orders_supplier_id'), 'purchase_orders', ['supplier_id'], unique=False)
    op.create_index(op.f('ix_purchase_orders_venue_id'), 'purchase_orders', ['venue_id'], unique=False)
    op.create_table('delivery_issues',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('issue_type', sa.Enum('short_delivery', 'damaged', 'wrong_item', 'late', 'quality', 'other', name='delivery_issue_type'), nullable=False),
    sa.Column('evidence', sa.String(length=500), nullable=True),
    sa.Column('resolution', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_issues_purchase_order_id'), 'delivery_issues', ['purchase_order_id'], unique=False)
    op.create_table('purchase_order_lines',
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=40), nullable=False),
    sa.Column('delivery_note', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_order_lines_ingredient_id'), 'purchase_order_lines', ['ingredient_id'], unique=False)
    op.create_index(op.f('ix_purchase_order_lines_purchase_order_id'), 'purchase_order_lines', ['purchase_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_order_lines_purchase_order_id'), table_name='purchase_order_lines')
    op.drop_index(op.f('ix_purchase_order_lines_ingredient_id'), table_name='purchase_order_lines')
    op.drop_table('purchase_order_lines')
    op.drop_index(op.f('ix_delivery_issues_purchase_order_id'), table_name='delivery_issues')
    op.drop_table('delivery_issues')
    op.drop_index(op.f('ix_purchase_orders_venue_id'), table_name='purchase_orders')
    op.drop_index(op.f('ix_purchase_orders_supplier_id'), table_name='purchase_orders')
    op.drop_table('purchase_orders')
    # ### end Alembic commands ###

    # Postgres ENUM types are not auto-dropped by the table drops above —
    # same fix applied to every migration since 0003.
    sa.Enum(name="delivery_issue_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="delivery_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="purchase_order_status").drop(op.get_bind(), checkfirst=True)
