"""epic6 quick capture

Revision ID: 0007_epic6
Revises: 0006_epic5
Create Date: 2026-09-17 14:39:02.824196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0007_epic6'
down_revision = '0006_epic5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('captures',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('capture_type', sa.Enum('restock', 'eighty_six', 'equipment_issue', 'unparsed', name='capture_type'), nullable=False),
    sa.Column('matched_entity_type', sa.Enum('ingredient', 'menu_item', 'equipment_item', name='matched_entity_type'), nullable=True),
    sa.Column('matched_entity_id', sa.UUID(), nullable=True),
    sa.Column('extracted_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('extracted_unit', sa.String(length=40), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('candidate_matches', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('proposed', 'confirmed', 'rejected', name='capture_status'), nullable=False),
    sa.Column('decided_by', sa.UUID(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_captures_service_day_id'), 'captures', ['service_day_id'], unique=False)
    op.create_index(op.f('ix_captures_venue_id'), 'captures', ['venue_id'], unique=False)
    op.create_table('equipment_issues',
    sa.Column('equipment_item_id', sa.UUID(), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='equipment_issue_priority'), nullable=False),
    sa.Column('status', sa.Enum('open', 'resolved', name='equipment_issue_status'), nullable=False),
    sa.Column('photos', sa.String(length=1000), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['equipment_item_id'], ['equipment_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_issues_equipment_item_id'), 'equipment_issues', ['equipment_item_id'], unique=False)
    op.create_table('menu_availability_events',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('available', 'low', 'unavailable', name='menu_availability_status'), nullable=False),
    sa.Column('quantity_remaining', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('recorded_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_menu_availability_events_menu_item_id'), 'menu_availability_events', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_menu_availability_events_service_day_id'), 'menu_availability_events', ['service_day_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_menu_availability_events_service_day_id'), table_name='menu_availability_events')
    op.drop_index(op.f('ix_menu_availability_events_menu_item_id'), table_name='menu_availability_events')
    op.drop_table('menu_availability_events')
    op.drop_index(op.f('ix_equipment_issues_equipment_item_id'), table_name='equipment_issues')
    op.drop_table('equipment_issues')
    op.drop_index(op.f('ix_captures_venue_id'), table_name='captures')
    op.drop_index(op.f('ix_captures_service_day_id'), table_name='captures')
    op.drop_table('captures')
    # ### end Alembic commands ###

    # Postgres ENUM types are not auto-dropped by the table drops above —
    # same fix applied to every migration since 0003.
    sa.Enum(name="menu_availability_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="equipment_issue_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="equipment_issue_priority").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="capture_status").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="matched_entity_type").drop(op.get_bind(), checkfirst=True)
    sa.Enum(name="capture_type").drop(op.get_bind(), checkfirst=True)
