"""epic7 handover

Revision ID: 0008_epic7
Revises: 0007_epic6
Create Date: 2026-09-17 14:53:26.193302

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0008_epic7'
down_revision = '0007_epic6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('handovers',
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('service_day_id', sa.UUID(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('closed_by', sa.UUID(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_to_close_seconds', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['closed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['service_day_id'], ['service_days.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handovers_service_day_id'), 'handovers', ['service_day_id'], unique=True)
    op.create_index(op.f('ix_handovers_venue_id'), 'handovers', ['venue_id'], unique=False)
    op.create_table('handover_items',
    sa.Column('handover_id', sa.UUID(), nullable=False),
    sa.Column('included', sa.Boolean(), nullable=False),
    sa.Column('prep_task_id', sa.UUID(), nullable=True),
    sa.Column('capture_id', sa.UUID(), nullable=True),
    sa.Column('equipment_issue_id', sa.UUID(), nullable=True),
    sa.Column('purchase_order_id', sa.UUID(), nullable=True),
    sa.Column('menu_availability_event_id', sa.UUID(), nullable=True),
    sa.Column('delivery_issue_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('(CASE WHEN prep_task_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN capture_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN equipment_issue_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN purchase_order_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN menu_availability_event_id IS NOT NULL THEN 1 ELSE 0 END + CASE WHEN delivery_issue_id IS NOT NULL THEN 1 ELSE 0 END) = 1', name='ck_handover_item_exactly_one_reference'),
    sa.ForeignKeyConstraint(['capture_id'], ['captures.id'], ),
    sa.ForeignKeyConstraint(['delivery_issue_id'], ['delivery_issues.id'], ),
    sa.ForeignKeyConstraint(['equipment_issue_id'], ['equipment_issues.id'], ),
    sa.ForeignKeyConstraint(['handover_id'], ['handovers.id'], ),
    sa.ForeignKeyConstraint(['menu_availability_event_id'], ['menu_availability_events.id'], ),
    sa.ForeignKeyConstraint(['prep_task_id'], ['prep_tasks.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_handover_items_capture_id'), 'handover_items', ['capture_id'], unique=False)
    op.create_index(op.f('ix_handover_items_delivery_issue_id'), 'handover_items', ['delivery_issue_id'], unique=False)
    op.create_index(op.f('ix_handover_items_equipment_issue_id'), 'handover_items', ['equipment_issue_id'], unique=False)
    op.create_index(op.f('ix_handover_items_handover_id'), 'handover_items', ['handover_id'], unique=False)
    op.create_index(op.f('ix_handover_items_menu_availability_event_id'), 'handover_items', ['menu_availability_event_id'], unique=False)
    op.create_index(op.f('ix_handover_items_prep_task_id'), 'handover_items', ['prep_task_id'], unique=False)
    op.create_index(op.f('ix_handover_items_purchase_order_id'), 'handover_items', ['purchase_order_id'], unique=False)
    # server_default so this NOT NULL column can't fail on a deployed DB
    # that already has rows — the ORM always sets it explicitly for new
    # rows going forward, but existing rows backfill to False (never
    # "added after close", correctly, since they predate this column).
    op.add_column('captures', sa.Column('added_after_close', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('prep_tasks', sa.Column('added_after_close', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prep_tasks', 'added_after_close')
    op.drop_column('captures', 'added_after_close')
    op.drop_index(op.f('ix_handover_items_purchase_order_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_prep_task_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_menu_availability_event_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_handover_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_equipment_issue_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_delivery_issue_id'), table_name='handover_items')
    op.drop_index(op.f('ix_handover_items_capture_id'), table_name='handover_items')
    op.drop_table('handover_items')
    op.drop_index(op.f('ix_handovers_venue_id'), table_name='handovers')
    op.drop_index(op.f('ix_handovers_service_day_id'), table_name='handovers')
    op.drop_table('handovers')
    # ### end Alembic commands ###
