"""epic9 kitchen memory

Revision ID: 0009_epic9
Revises: 0008_epic7
Create Date: 2026-09-17 22:08:31.758182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009_epic9'
down_revision = '0008_epic7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('suppliers', sa.Column('notes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('suppliers', 'notes')
    # ### end Alembic commands ###
